In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [16]:
arr[0:5]=100

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
arr = np.arange(0,11)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
slice_of_arr = arr[0:6]

In [21]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [22]:
slice_of_arr[:] = 99

In [23]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [24]:
arr_copy = arr.copy()

In [25]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d[0][0]

5

In [31]:
arr_2d > 20

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [32]:
bool_arr = arr_2d > 5

In [33]:
bool_arr

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [36]:
arr_2d[arr_2d > 10]

array([15, 20, 25, 30, 35, 40, 45])

In [37]:
arr_2d = np.arange(50).reshape(5,10)

In [38]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])