# Numpy Arrays - Aula 18

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(5)

array([0.51497654, 0.32147201, 0.26130426, 0.6678765 , 0.00826415])

In [27]:
np.random.rand(5,5)

array([[0.13493208, 0.17719034, 0.03674602, 0.84924077, 0.89532123],
       [0.23290033, 0.33348374, 0.00689539, 0.06229183, 0.49769079],
       [0.14766131, 0.35907355, 0.69954206, 0.76397514, 0.8622354 ],
       [0.77786514, 0.41937307, 0.77788948, 0.92427271, 0.3604837 ],
       [0.23775806, 0.36757768, 0.45962867, 0.3031775 , 0.50001263]])

In [29]:
np.random.randn(2)

array([-0.59924242,  0.41264583])

In [42]:
np.random.randint(1,100,10)

array([30, 10, 90, 31, 37,  9, 69, 61, 88, 91])

In [43]:
arr = np.arange(25)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr = np.random.randint(0,50,10)

In [46]:
ranarr

array([26, 45, 49, 34, 41, 15, 17,  2, 39, 22])

In [53]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
ranarr.max()

49

In [56]:
ranarr.min()

2

In [59]:
ranarr.argmin() #retorna o indice do menor valor do array

7

In [60]:
ranarr.argmax() #retorna o indice do maior valor do array

2

In [61]:
arr.shape

(25,)